import { contextBridge, ipcRenderer } from 'electron'

export interface FormattedVersion {
  id: string
  text: string
  timestamp: number
  sourceVersion: 'original' | string // 'original' or version id it was reformatted from
  customInstructions?: string // Custom instructions used for this reformat (if any)
}

export interface TranscriptionRecord {
  id: string
  text: string // The primary text (most recent formatted if available, otherwise original)
  originalText?: string // Raw transcription before formatting
  formattedText?: string // Legacy: first formatted version (kept for backward compatibility)
  formattedVersions?: FormattedVersion[] // Array of all formatted versions
  wasFormatted?: boolean // Whether formatting was applied
  title?: string // Short title/summary generated by formatter
  timestamp: number
  wordCount: number
  duration: number // Recording duration in seconds
}

export interface AppSettings {
  apiKey: string
  selectedMicrophoneId: string | null
  selectedTerminalId: string | null
  pasteHotkey: string
  recordHotkey: string
  replacementsEnabled: boolean
  voiceCommandsEnabled: boolean
  promptFormattingEnabled: boolean
  promptFormattingInstructions: string
  promptFormattingModel: 'sonnet' | 'opus' | 'haiku'
  historyLimit: number // 0 = no limit, otherwise max items to keep
}

export interface PromptFormattingSettings {
  enabled: boolean
  instructions: string
  model: 'sonnet' | 'opus' | 'haiku'
}

export interface FormatResult {
  success: boolean
  formatted: string
  error?: string
  skipped?: boolean
}

export interface ClaudeCliStatus {
  available: boolean
  version: string | null
}

export interface VoiceCommandTrigger {
  id: string
  phrase: string
  command: 'send' | 'clear' | 'cancel'
  enabled: boolean
  isCustom: boolean
}

export interface TerminalApp {
  name: string
  bundleId: string
  displayName: string
}

export interface TerminalWindow {
  appName: string
  bundleId: string
  windowName: string
  windowIndex: number
  displayName: string
}

export interface WordReplacement {
  id: string
  from: string
  to: string
  caseSensitive: boolean
  wholeWord: boolean
  enabled: boolean
}

export type RecordingToggleCallback = () => void
export type TranscriptionPastedCallback = (text: string) => void

const electronAPI = {
  // Token management
  getScribeToken: (): Promise<string> => ipcRenderer.invoke('get-scribe-token'),

  // Settings
  getSettings: (): Promise<AppSettings> => ipcRenderer.invoke('get-settings'),
  setSettings: (settings: Partial<AppSettings>): Promise<AppSettings> =>
    ipcRenderer.invoke('set-settings', settings),
  getApiKey: (): Promise<string> => ipcRenderer.invoke('get-api-key'),
  setApiKey: (apiKey: string): Promise<boolean> => ipcRenderer.invoke('set-api-key', apiKey),
  hasApiKey: (): Promise<boolean> => ipcRenderer.invoke('has-api-key'),

  // History
  getHistory: (): Promise<TranscriptionRecord[]> => ipcRenderer.invoke('get-history'),
  saveTranscription: (record: TranscriptionRecord): Promise<boolean> =>
    ipcRenderer.invoke('save-transcription', record),
  deleteTranscription: (id: string): Promise<boolean> =>
    ipcRenderer.invoke('delete-transcription', id),
  clearHistory: (): Promise<boolean> => ipcRenderer.invoke('clear-history'),
  getLastTranscription: (): Promise<TranscriptionRecord | null> =>
    ipcRenderer.invoke('get-last-transcription'),

  // Clipboard
  copyToClipboard: (text: string): Promise<boolean> =>
    ipcRenderer.invoke('copy-to-clipboard', text),
  readClipboard: (): Promise<string> => ipcRenderer.invoke('read-clipboard'),

  // Terminal operations
  getRunningTerminals: (): Promise<TerminalApp[]> =>
    ipcRenderer.invoke('get-running-terminals'),
  getSupportedTerminals: (): Promise<TerminalApp[]> =>
    ipcRenderer.invoke('get-supported-terminals'),
  pasteToTerminal: (text: string, bundleId: string): Promise<{ success: boolean; needsPermission: boolean; copied: boolean }> =>
    ipcRenderer.invoke('paste-to-terminal', text, bundleId),
  getTerminalWindows: (): Promise<TerminalWindow[]> =>
    ipcRenderer.invoke('get-terminal-windows'),
  pasteToTerminalWindow: (text: string, bundleId: string, windowName: string): Promise<{ success: boolean; needsPermission: boolean; copied: boolean }> =>
    ipcRenderer.invoke('paste-to-terminal-window', text, bundleId, windowName),
  pasteToLastActiveTerminal: (text: string): Promise<{ success: boolean; needsPermission: boolean; copied: boolean; targetApp: string | null }> =>
    ipcRenderer.invoke('paste-to-last-active-terminal', text),

  // Word replacement operations
  getReplacements: (): Promise<WordReplacement[]> =>
    ipcRenderer.invoke('get-replacements'),
  addReplacement: (replacement: WordReplacement): Promise<boolean> =>
    ipcRenderer.invoke('add-replacement', replacement),
  updateReplacement: (id: string, updates: Partial<WordReplacement>): Promise<boolean> =>
    ipcRenderer.invoke('update-replacement', id, updates),
  deleteReplacement: (id: string): Promise<boolean> =>
    ipcRenderer.invoke('delete-replacement', id),
  applyReplacements: (text: string): Promise<string> =>
    ipcRenderer.invoke('apply-replacements', text),

  // Voice command trigger operations
  getVoiceCommandTriggers: (): Promise<VoiceCommandTrigger[]> =>
    ipcRenderer.invoke('get-voice-command-triggers'),
  updateVoiceCommandTrigger: (id: string, updates: Partial<VoiceCommandTrigger>): Promise<boolean> =>
    ipcRenderer.invoke('update-voice-command-trigger', id, updates),
  addVoiceCommandTrigger: (trigger: VoiceCommandTrigger): Promise<boolean> =>
    ipcRenderer.invoke('add-voice-command-trigger', trigger),
  deleteVoiceCommandTrigger: (id: string): Promise<boolean> =>
    ipcRenderer.invoke('delete-voice-command-trigger', id),
  resetVoiceCommandTriggers: (): Promise<boolean> =>
    ipcRenderer.invoke('reset-voice-command-triggers'),
  getEnabledVoiceCommands: (): Promise<{ send: string[], clear: string[], cancel: string[] }> =>
    ipcRenderer.invoke('get-enabled-voice-commands'),

  // Hotkey operations
  updateHotkey: (type: 'paste' | 'record', newHotkey: string): Promise<{ success: boolean; error?: string }> =>
    ipcRenderer.invoke('update-hotkey', type, newHotkey),

  // Prompt formatting operations
  formatPrompt: (text: string): Promise<{ success: boolean; formatted: string; error?: string; skipped?: boolean }> =>
    ipcRenderer.invoke('format-prompt', text),
  getPromptFormattingSettings: (): Promise<{ enabled: boolean; instructions: string; model: 'sonnet' | 'opus' | 'haiku' }> =>
    ipcRenderer.invoke('get-prompt-formatting-settings'),
  setPromptFormattingEnabled: (enabled: boolean): Promise<boolean> =>
    ipcRenderer.invoke('set-prompt-formatting-enabled', enabled),
  setPromptFormattingInstructions: (instructions: string): Promise<boolean> =>
    ipcRenderer.invoke('set-prompt-formatting-instructions', instructions),
  setPromptFormattingModel: (model: 'sonnet' | 'opus' | 'haiku'): Promise<boolean> =>
    ipcRenderer.invoke('set-prompt-formatting-model', model),
  getDefaultFormattingInstructions: (): Promise<string> =>
    ipcRenderer.invoke('get-default-formatting-instructions'),
  checkClaudeCli: (): Promise<{ available: boolean; version: string | null }> =>
    ipcRenderer.invoke('check-claude-cli'),
  generateTitle: (text: string): Promise<{ success: boolean; title: string; error?: string }> =>
    ipcRenderer.invoke('generate-title', text),
  reformatText: (text: string, customInstructions?: string): Promise<{ success: boolean; formatted: string; error?: string }> =>
    ipcRenderer.invoke('reformat-text', text, customInstructions),

  // Events from main process
  onToggleRecording: (callback: RecordingToggleCallback): void => {
    ipcRenderer.on('toggle-recording', () => callback())
  },
  onTranscriptionPasted: (callback: TranscriptionPastedCallback): void => {
    ipcRenderer.on('transcription-pasted', (_, text: string) => callback(text))
  },
  onPasteLastTranscription: (callback: () => void): void => {
    ipcRenderer.on('paste-last-transcription', () => callback())
  },
  onHistoryChanged: (callback: () => void): void => {
    ipcRenderer.on('history-changed', () => callback())
  },

  // Remove listeners
  removeAllListeners: (channel: string): void => {
    ipcRenderer.removeAllListeners(channel)
  },

  // Notify main process of recording state
  notifyRecordingState: (isRecording: boolean): void => {
    ipcRenderer.send('recording-state-changed', isRecording)
  }
}

// Expose API to renderer
contextBridge.exposeInMainWorld('electronAPI', electronAPI)

// Type declaration for TypeScript
export type ElectronAPI = typeof electronAPI
