import { contextBridge, ipcRenderer } from 'electron'

export interface FormattedVersion {
  id: string
  text: string
  timestamp: number
  sourceVersion: 'original' | string // 'original' or version id it was reformatted from
  customInstructions?: string // Custom instructions used for this reformat (if any)
}

export interface TranscriptionRecord {
  id: string
  text: string // The primary text (most recent formatted if available, otherwise original)
  originalText?: string // Raw transcription before formatting
  formattedText?: string // Legacy: first formatted version (kept for backward compatibility)
  formattedVersions?: FormattedVersion[] // Array of all formatted versions
  wasFormatted?: boolean // Whether formatting was applied
  title?: string // Short title/summary generated by formatter
  timestamp: number
  wordCount: number
  duration: number // Recording duration in seconds
}

export interface AppSettings {
  apiKey: string
  deepgramApiKey: string
  selectedMicrophoneId: string | null
  selectedTerminalId: string | null
  pasteHotkey: string
  recordHotkey: string
  recordWithFormattingHotkey: string
  submitAfterPaste: boolean
  replacementsEnabled: boolean
  voiceCommandsEnabled: boolean
  promptFormattingEnabled: boolean
  promptFormattingInstructions: string
  promptFormattingModel: 'sonnet' | 'opus' | 'haiku'
  historyLimit: number // 0 = no limit, otherwise max items to keep
  pasteMode: 'auto' | 'clipboard' | 'terminal'
  hasCompletedFirstLaunch: boolean
  showPasteNotifications: boolean
  transcriptionEngine: 'elevenlabs' | 'deepgram' // Transcription provider
  deepgramApiKey: string
  deepgramModel: 'nova-3' | 'nova-3-monolingual' | 'nova-3-multilingual' | 'nova-2' | 'flux' // Deepgram model selection
}

export interface PromptFormattingSettings {
  enabled: boolean
  instructions: string
  model: 'sonnet' | 'opus' | 'haiku'
}

export interface FormatResult {
  success: boolean
  formatted: string
  error?: string
  skipped?: boolean
}

export interface ClaudeCliStatus {
  available: boolean
  version: string | null
}

export interface VoiceCommandTrigger {
  id: string
  phrase: string
  command: 'send' | 'clear' | 'cancel'
  enabled: boolean
  isCustom: boolean
}

export interface TerminalApp {
  name: string
  bundleId: string
  displayName: string
}

export interface TerminalWindow {
  appName: string
  bundleId: string
  windowName: string
  windowIndex: number
  displayName: string
}

export interface WordReplacement {
  id: string
  from: string
  to: string
  caseSensitive: boolean
  wholeWord: boolean
  enabled: boolean
}

export type RecordingToggleCallback = (withFormatting: boolean) => void
export type TranscriptionPastedCallback = (text: string) => void

export interface HistoryStats {
  totalRecords: number
  totalWords: number
  totalDuration: number
  formattedCount: number
  averageWordCount: number
  averageDuration: number
}

const electronAPI = {
  // Token management
  getScribeToken: (): Promise<string> => ipcRenderer.invoke('get-scribe-token'),

  // Settings
  getSettings: (): Promise<AppSettings> => ipcRenderer.invoke('get-settings'),
  setSettings: (settings: Partial<AppSettings>): Promise<AppSettings> =>
    ipcRenderer.invoke('set-settings', settings),
  getApiKey: (): Promise<string> => ipcRenderer.invoke('get-api-key'),
  setApiKey: (apiKey: string): Promise<boolean> => ipcRenderer.invoke('set-api-key', apiKey),
  hasApiKey: (): Promise<boolean> => ipcRenderer.invoke('has-api-key'),
  getDeepgramApiKey: (): Promise<string> => ipcRenderer.invoke('get-deepgram-api-key'),
  setDeepgramApiKey: (apiKey: string): Promise<boolean> =>
    ipcRenderer.invoke('set-deepgram-api-key', apiKey),
  hasDeepgramApiKey: (): Promise<boolean> => ipcRenderer.invoke('has-deepgram-api-key'),

  // History
  getHistory: (): Promise<TranscriptionRecord[]> => ipcRenderer.invoke('get-history'),
  saveTranscription: (record: TranscriptionRecord): Promise<boolean> =>
    ipcRenderer.invoke('save-transcription', record),
  deleteTranscription: (id: string): Promise<boolean> =>
    ipcRenderer.invoke('delete-transcription', id),
  clearHistory: (): Promise<boolean> => ipcRenderer.invoke('clear-history'),
  getLastTranscription: (): Promise<TranscriptionRecord | null> =>
    ipcRenderer.invoke('get-last-transcription'),
  getHistoryStats: (): Promise<HistoryStats> => ipcRenderer.invoke('get-history-stats'),

  // Clipboard
  copyToClipboard: (text: string): Promise<boolean> =>
    ipcRenderer.invoke('copy-to-clipboard', text),
  readClipboard: (): Promise<string> => ipcRenderer.invoke('read-clipboard'),

  // Terminal operations
  getRunningTerminals: (): Promise<TerminalApp[]> => ipcRenderer.invoke('get-running-terminals'),
  getSupportedTerminals: (): Promise<TerminalApp[]> =>
    ipcRenderer.invoke('get-supported-terminals'),
  pasteToTerminal: (
    text: string,
    bundleId: string
  ): Promise<{ success: boolean; needsPermission: boolean; copied: boolean }> =>
    ipcRenderer.invoke('paste-to-terminal', text, bundleId),
  getTerminalWindows: (): Promise<TerminalWindow[]> => ipcRenderer.invoke('get-terminal-windows'),
  pasteToTerminalWindow: (
    text: string,
    bundleId: string,
    windowName: string
  ): Promise<{ success: boolean; needsPermission: boolean; copied: boolean }> =>
    ipcRenderer.invoke('paste-to-terminal-window', text, bundleId, windowName),
  pasteToLastActiveTerminal: (
    text: string
  ): Promise<{
    success: boolean
    needsPermission: boolean
    copied: boolean
    targetApp: string | null
  }> => ipcRenderer.invoke('paste-to-last-active-terminal', text),

  // Paste mode operations
  getPasteMode: (): Promise<'auto' | 'clipboard' | 'terminal'> =>
    ipcRenderer.invoke('get-paste-mode'),
  setPasteMode: (mode: 'auto' | 'clipboard' | 'terminal'): Promise<boolean> =>
    ipcRenderer.invoke('set-paste-mode', mode),
  pasteText: (
    text: string,
    mode?: 'auto' | 'clipboard' | 'terminal'
  ): Promise<{ success: boolean; mode: string; error?: string }> =>
    ipcRenderer.invoke('paste-text', text, mode),
  checkAccessibilityPermissions: (): Promise<boolean> =>
    ipcRenderer.invoke('check-accessibility-permissions'),
  requestAccessibilityPermissions: (): Promise<boolean> =>
    ipcRenderer.invoke('request-accessibility-permissions'),

  // Generic invoke method (for flexibility)
  invoke: (channel: string, ...args: unknown[]): Promise<unknown> =>
    ipcRenderer.invoke(channel, ...args),

  // Word replacement operations
  getReplacements: (): Promise<WordReplacement[]> => ipcRenderer.invoke('get-replacements'),
  addReplacement: (replacement: WordReplacement): Promise<boolean> =>
    ipcRenderer.invoke('add-replacement', replacement),
  updateReplacement: (id: string, updates: Partial<WordReplacement>): Promise<boolean> =>
    ipcRenderer.invoke('update-replacement', id, updates),
  deleteReplacement: (id: string): Promise<boolean> => ipcRenderer.invoke('delete-replacement', id),
  applyReplacements: (text: string): Promise<string> =>
    ipcRenderer.invoke('apply-replacements', text),

  // Voice command trigger operations
  getVoiceCommandTriggers: (): Promise<VoiceCommandTrigger[]> =>
    ipcRenderer.invoke('get-voice-command-triggers'),
  updateVoiceCommandTrigger: (
    id: string,
    updates: Partial<VoiceCommandTrigger>
  ): Promise<boolean> => ipcRenderer.invoke('update-voice-command-trigger', id, updates),
  addVoiceCommandTrigger: (trigger: VoiceCommandTrigger): Promise<boolean> =>
    ipcRenderer.invoke('add-voice-command-trigger', trigger),
  deleteVoiceCommandTrigger: (id: string): Promise<boolean> =>
    ipcRenderer.invoke('delete-voice-command-trigger', id),
  resetVoiceCommandTriggers: (): Promise<boolean> =>
    ipcRenderer.invoke('reset-voice-command-triggers'),
  getEnabledVoiceCommands: (): Promise<{ send: string[]; clear: string[]; cancel: string[] }> =>
    ipcRenderer.invoke('get-enabled-voice-commands'),

  // Hotkey operations
  updateHotkey: (
    type: 'paste' | 'record' | 'recordWithFormatting',
    newHotkey: string
  ): Promise<{ success: boolean; error?: string }> =>
    ipcRenderer.invoke('update-hotkey', type, newHotkey),

  // Prompt formatting operations
  formatPrompt: (
    text: string
  ): Promise<{ success: boolean; formatted: string; error?: string; skipped?: boolean }> =>
    ipcRenderer.invoke('format-prompt', text),
  getPromptFormattingSettings: (): Promise<{
    enabled: boolean
    instructions: string
    model: 'sonnet' | 'opus' | 'haiku'
  }> => ipcRenderer.invoke('get-prompt-formatting-settings'),
  setPromptFormattingEnabled: (enabled: boolean): Promise<boolean> =>
    ipcRenderer.invoke('set-prompt-formatting-enabled', enabled),
  setPromptFormattingInstructions: (instructions: string): Promise<boolean> =>
    ipcRenderer.invoke('set-prompt-formatting-instructions', instructions),
  setPromptFormattingModel: (model: 'sonnet' | 'opus' | 'haiku'): Promise<boolean> =>
    ipcRenderer.invoke('set-prompt-formatting-model', model),
  getDefaultFormattingInstructions: (): Promise<string> =>
    ipcRenderer.invoke('get-default-formatting-instructions'),
  checkClaudeCli: (): Promise<{ available: boolean; version: string | null }> =>
    ipcRenderer.invoke('check-claude-cli'),
  generateTitle: (text: string): Promise<{ success: boolean; title: string; error?: string }> =>
    ipcRenderer.invoke('generate-title', text),
  reformatText: (
    text: string,
    customInstructions?: string
  ): Promise<{ success: boolean; formatted: string; error?: string }> =>
    ipcRenderer.invoke('reformat-text', text, customInstructions),

  // Gamification operations
  getGamificationData: () => ipcRenderer.invoke('get-gamification-data'),
  getAchievementDefinitions: () => ipcRenderer.invoke('get-achievement-definitions'),
  getAnalyticsData: (range: string, dateRange?: { start: Date; end: Date }) =>
    ipcRenderer.invoke('get-analytics-data', range, dateRange),
  saveGamificationData: (data: unknown) => ipcRenderer.invoke('save-gamification-data', data),
  recordGamificationSession: (params: { words: number; durationMs: number }) =>
    ipcRenderer.invoke('record-gamification-session', params),
  unlockGamificationAchievement: (params: { achievementId: string; xpReward: number }) =>
    ipcRenderer.invoke('unlock-gamification-achievement', params),
  checkGamificationDailyLogin: () => ipcRenderer.invoke('check-gamification-daily-login'),
  resetGamificationProgress: () => ipcRenderer.invoke('reset-gamification-progress'),
  checkAndUnlockAllAchievements: () => ipcRenderer.invoke('check-and-unlock-all-achievements'),
  trackFeatureUsage: (featureType: string, metadata?: { bundleId?: string }): Promise<string[]> =>
    ipcRenderer.invoke('track-feature-usage', featureType, metadata),
  resetAchievement: (achievementId: string): Promise<{ success: boolean; wasUnlocked: boolean }> =>
    ipcRenderer.invoke('reset-achievement', achievementId),
  onGamificationDataChanged: (callback: () => void): void => {
    ipcRenderer.on('gamification-data-changed', () => callback())
  },
  onAchievementUnlocked: (callback: (achievementId: string) => void): void => {
    ipcRenderer.on('achievement-unlocked', (_, achievementId: string) => callback(achievementId))
  },

  // Events from main process
  onToggleRecording: (callback: RecordingToggleCallback): void => {
    ipcRenderer.on('toggle-recording', (_, withFormatting: boolean) => callback(withFormatting))
  },
  onTranscriptionPasted: (callback: TranscriptionPastedCallback): void => {
    ipcRenderer.on('transcription-pasted', (_, text: string) => callback(text))
  },
  onPasteLastTranscription: (callback: () => void): void => {
    ipcRenderer.on('paste-last-transcription', () => callback())
  },
  onHistoryChanged: (callback: () => void): void => {
    ipcRenderer.on('history-changed', () => callback())
  },

  // Remove listeners
  removeAllListeners: (channel: string): void => {
    ipcRenderer.removeAllListeners(channel)
  },

  // Notify main process of recording state
  notifyRecordingState: (isRecording: boolean): void => {
    ipcRenderer.send('recording-state-changed', isRecording)
  },

  // Send audio level to main process (for overlay visualization)
  sendAudioLevel: (level: number): void => {
    ipcRenderer.send('audio-level', level)
  },

  // Send frequency data to main process (for spectrum visualization)
  sendFrequencyData: (frequencyData: number[]): void => {
    ipcRenderer.send('frequency-data', frequencyData)
  },

  // Send recording time to main process (for overlay display)
  sendRecordingTime: (seconds: number): void => {
    ipcRenderer.send('recording-time', seconds)
  },

  // Send voice commands to main process (for overlay display)
  sendVoiceCommands: (commands: { send: string[]; clear: string[]; cancel: string[] }): void => {
    ipcRenderer.send('voice-commands-update', commands)
  },

  // Send live transcript preview to main process (for overlay display)
  sendTranscriptPreview: (text: string, wordCount: number): void => {
    ipcRenderer.send('transcript-preview', { text, wordCount })
  },

  // Send overlay status info to main process
  sendOverlayStatus: (status: { connected: boolean; formattingEnabled: boolean }): void => {
    ipcRenderer.send('overlay-status', status)
  },

  // Test methods for formatting overlay
  testShowFormattingOverlay: (): void => {
    ipcRenderer.send('test-show-formatting-overlay')
  },

  testHideFormattingOverlay: (): void => {
    ipcRenderer.send('test-hide-formatting-overlay')
  },

  // Send comparison selection from overlay
  sendComparisonSelection: (selectedText: string): void => {
    ipcRenderer.send('comparison-text-selected', selectedText)
  },

  // Cancel overlay (triggered by Escape key)
  cancelOverlay: (): void => {
    ipcRenderer.send('cancel-overlay')
  },

  // Transcription engine selection
  getTranscriptionEngine: (): Promise<'elevenlabs' | 'deepgram'> =>
    ipcRenderer.invoke('get-transcription-engine'),
  setTranscriptionEngine: (engine: 'elevenlabs' | 'deepgram'): Promise<boolean> =>
    ipcRenderer.invoke('set-transcription-engine', engine),

  // API connection testing
  testDeepgramConnection: (): Promise<{ success: boolean; error?: string }> =>
    ipcRenderer.invoke('test-deepgram-connection'),

  // Error logging
  logError: (error: { message: string; stack: string; componentStack?: string }): void => {
    ipcRenderer.send('log-error', error)
  },
}

// Expose API to renderer
contextBridge.exposeInMainWorld('electronAPI', electronAPI)

// Type declaration for TypeScript
export type ElectronAPI = typeof electronAPI
