name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: The application crashes when...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
      placeholder: I expected the application to...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened
      placeholder: Instead, the application...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of the operating system? (e.g., macOS 14.0, Windows 11, Ubuntu 22.04)
      placeholder: "macOS 14.0"
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of Neural Scribe are you using? (Check in Help → About)
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any relevant console logs or error messages. You can find logs in the developer console (Help → Toggle Developer Tools)
      render: shell
      placeholder: |
        Paste logs here...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. Drag and drop images here.
      placeholder: Drag and drop screenshots here

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of Neural Scribe
          required: true
        - label: I have included all requested information above
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here (e.g., workarounds, frequency, impact)
      placeholder: This happens every time I...
