name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: I'm frustrated when... / It would be helpful to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? Be as specific as possible.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or features have you considered?
      placeholder: I also thought about... / Other approaches I considered...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples from other applications
      placeholder: Drag and drop images or provide links to examples

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      description: Help us prioritize by indicating the importance
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Are you willing to contribute?
      description: Would you be able to help implement this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, with guidance"
        - "No, I'm just suggesting"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, links, or resources about the feature request here
      placeholder: Related discussions, similar features in other apps, etc.
