name: Question
description: Ask a question about Neural Scribe
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about Neural Scribe? Ask away!

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Usage / How to
        - Configuration / Settings
        - Architecture / Design
        - API / Integration
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question in detail
      placeholder: How do I...? / What is the best way to...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context (what you're trying to achieve, what you've already tried, etc.)
      placeholder: I'm trying to... / I've already tried...

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using? (if relevant)
      options:
        - macOS
        - Windows
        - Linux
        - Not applicable

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of Neural Scribe are you using? (if relevant)
      placeholder: "1.0.0"

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues and documentation
          required: true
        - label: This is not a bug report or feature request
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Any other information that might be helpful
      placeholder: Related documentation, links, screenshots, etc.
